server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learnjapanesedb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  mail:
    host: bartlomiej-swies.pl
    port: 587
    username: :-)
    password: :-)
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
application:
  jwt:
    secretKey: :-)
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14